// Measure the live site with Lighthouse and write src/data/performance.ts.
// The process page renders THESE numbers — they come from an actual run, not markup.
// Usage: node scripts/measure.mjs [url]   (default https://itzpratham.in/)
import { spawnSync } from "node:child_process";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const url = process.argv[2] ?? "https://itzpratham.in/?noloader=1&theme=light";
const out = join(tmpdir(), `lh-${Date.now()}.json`);

console.log(`measuring ${url} …`);
const res = spawnSync(
  "npx",
  [
    "lighthouse",
    url,
    "--quiet",
    "--chrome-flags=--headless --no-sandbox",
    "--only-categories=performance,accessibility,best-practices,seo",
    "--output=json",
    `--output-path=${out}`,
  ],
  { stdio: "inherit", shell: process.platform === "win32" }
);

if (!existsSync(out)) {
  console.error("lighthouse produced no report (exit " + res.status + ")");
  process.exit(1);
}

const report = JSON.parse(readFileSync(out, "utf8"));
const a = report.audits;
const round = (v) => Math.round(v * 100);

const data = {
  measuredAt: new Date().toISOString(),
  measuredAtLabel: new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }),
  url,
  scores: {
    perf: round(report.categories.performance.score),
    a11y: round(report.categories.accessibility.score),
    bp: round(report.categories["best-practices"].score),
    seo: round(report.categories.seo.score),
  },
  metrics: {
    lcp: a["largest-contentful-paint"].displayValue,
    fcp: a["first-contentful-paint"].displayValue,
    tbt: a["total-blocking-time"].displayValue,
    cls: a["cumulative-layout-shift"].displayValue,
  },
};

const ts = `// Auto-generated by scripts/measure.mjs — do not edit by hand.
// Updated on every deploy: npm run measure → live Lighthouse run against ${url}
export const performanceData = ${JSON.stringify(data, null, 2)};
`;

writeFileSync(new URL("../src/data/performance.ts", import.meta.url), ts, "utf8");
console.log("wrote src/data/performance.ts");
console.log(JSON.stringify(data, null, 2));
