// Auto-generated by scripts/measure.mjs — do not edit by hand.
// Updated on every deploy: npm run measure → live Lighthouse run against https://itzpratham.in/?noloader=1&theme=light
export const performanceData = {
  "measuredAt": "2026-08-22T09:49:06.436Z",
  "measuredAtLabel": "22 Aug 2026",
  "url": "https://itzpratham.in/?noloader=1&theme=light",
  "scores": {
    "perf": 63,
    "a11y": 100,
    "bp": 100,
    "seo": 100
  },
  "metrics": {
    "lcp": "3.7 s",
    "fcp": "1.7 s",
    "tbt": "1,000 ms",
    "cls": "0"
  }
};
