// Auto-generated by scripts/measure.mjs — do not edit by hand.
// Updated on every deploy: npm run measure → live Lighthouse run against https://itzpratham.in/?noloader=1&theme=light
export const performanceData = {
  "measuredAt": "2026-08-13T00:27:35.253Z",
  "measuredAtLabel": "13 Aug 2026",
  "url": "https://itzpratham.in/?noloader=1&theme=light",
  "scores": {
    "perf": 61,
    "a11y": 100,
    "bp": 100,
    "seo": 100
  },
  "metrics": {
    "lcp": "4.0 s",
    "fcp": "2.0 s",
    "tbt": "970 ms",
    "cls": "0"
  }
};
