// Auto-generated by scripts/measure.mjs — do not edit by hand.
// Updated on every deploy: npm run measure → live Lighthouse run against https://itzpratham.in/?noloader=1&theme=light
export const performanceData = {
  "measuredAt": "2026-08-12T02:06:02.688Z",
  "measuredAtLabel": "12 Aug 2026",
  "url": "https://itzpratham.in/?noloader=1&theme=light",
  "scores": {
    "perf": 55,
    "a11y": 96,
    "bp": 96,
    "seo": 100
  },
  "metrics": {
    "lcp": "3.7 s",
    "fcp": "2.0 s",
    "tbt": "1,860 ms",
    "cls": "0"
  }
};
